
name: CI
on:
  push:
    branches:
      - "**"

jobs:
  unit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: setup-Node18
        with:
          node-version: '18.x'
          registry-url: https://registry.npmjs.org
          
      - run: yarn install --frozen-lockfile
      - run: npm publish --access public 
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
            
