
name: CI
on:
  push:
    branches:
      - "**"

jobs:
  unit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn run test
