
name: CI
on:
  push:
    branches:
      - "**"

jobs:
  unit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: setup-Node18
        with:
          node-version: '18.x'
          
      - run: echo "@bit:registry=https://node.bit.dev\n//node.bit.dev/:_authToken=$NPM_TOKEN" >> $HOME/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: yarn install --frozen-lockfile
            
